### ISSUE TITLE
安卓13打开崩溃

### ISSUE THREAD

**Issue by fcwys** [jing332/FrpAndroid#1]
建议不要强制跳转电源策略，否则安卓13一直闪退

**Comment by jing332** [comment]
你确定是这个问题么？ 有崩溃日志嘛？
正常来说 崩溃日志会复制到剪贴板

**Comment by jing332** [comment]
ok 修了，从action下载

**Comment by fcwys** [comment]
崩溃日志：
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Tombstone maker: 'xCrash 3.0.0'
Crash type: 'java'
Start time: '2023-08-21T23:34:45.314+0800'
Crash time: '2023-08-21T23:34:45.825+0800'
App ID: 'com.github.jing332.frpandroid'
App version: '1.23.082122 (23)'
Rooted: 'No'
API level: '33'
OS version: '13'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'Xiaomi'
Brand: 'Redmi'
Model: 'Redmi K40S'
Build fingerprint: 'Redmi/munch/munch:13/TKQ1.220807.001/V14.0.6.0.TLMCNXM:user/release-keys'
pid: 2443, tid: 2443, name: main  >>> com.github.jing332.frpandroid <<<

java stacktrace:
java.io.IOException: Cannot run program "/data/app/~~PZ0Iu8WddmCb9FN7aQ8YYA==/com.github.jing332.frpandroid-D36q6AJjBVNNYE49-jqZog==/lib/arm64/frpc.so": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at u4.d.a(Frp.kt:33)
	at u4.d.c(Frp.kt:7)
	at z4.g0$a$a.i(FrpcScreen.kt:13)
	at d6.a.o(ContinuationImpl.kt:9)
	at y6.l0.run(DispatchedTask.kt:111)
	at d7.k$a.run(LimitedDispatcher.kt:4)
	at f7.j.run(Tasks.kt:3)
	at f7.a$a.run(CoroutineScheduler.kt:94)
	Suppressed: d7.h: [androidx.compose.ui.platform.h2@ac567fb, h0.e@2ddf018, s1{Cancelling}@236ba71, Dispatchers.Main]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

logcat:
--------- tail end of log main (/system/bin/logcat -b main -d -v threadtime -t 200 --pid 2443 *:D)
--------- beginning of main
08-21 23:34:45.241  2443  2443 E g332.frpandroid: Not starting debugger since process cannot load the jdwp agent.
08-21 23:34:45.246  2443  2443 I MessageMonitor: Load libmiui_runtime
08-21 23:34:45.257  2443  2460 D AppScoutStateMachine: 2443-ScoutStateMachinecreated
08-21 23:34:45.260  2443  2443 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10695; state: ENABLED
08-21 23:34:45.266  2443  2443 W ziparchive: Unable to open '/data/app/~~PZ0Iu8WddmCb9FN7aQ8YYA==/com.github.jing332.frpandroid-D36q6AJjBVNNYE49-jqZog==/base.dm': No such file or directory
08-21 23:34:45.266  2443  2443 W ziparchive: Unable to open '/data/app/~~PZ0Iu8WddmCb9FN7aQ8YYA==/com.github.jing332.frpandroid-D36q6AJjBVNNYE49-jqZog==/base.dm': No such file or directory
08-21 23:34:45.303  2443  2443 I Perf    : Connecting to perf service.
08-21 23:34:45.307  2443  2443 I ForceDarkHelperStubImpl: initialize for com.github.jing332.frpandroid , ForceDarkOrigin
08-21 23:34:45.308  2443  2443 D g332.frpandroid: JNI_OnLoad success
08-21 23:34:45.308  2443  2443 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
08-21 23:34:45.308  2443  2443 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
08-21 23:34:45.308  2443  2443 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
08-21 23:34:45.378  2443  2443 W libc    : Access denied finding property "ro.vendor.df.effect.conflict"
08-21 23:34:45.384  2443  2443 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 23:34:45.394  2443  2478 D ViewContentFactory: initViewContentFetcherClass
08-21 23:34:45.394  2443  2478 D ViewContentFactory: getInterceptorPackageInfo
08-21 23:34:45.394  2443  2478 D ViewContentFactory: getInitialApplication took 0ms
08-21 23:34:45.394  2443  2478 D ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
08-21 23:34:45.397  2443  2478 D ViewContentFactory: initViewContentFetcherClass took 3ms
08-21 23:34:45.397  2443  2478 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 23:34:45.397  2443  2478 D ViewContentFactory: createInterceptor took 3ms
08-21 23:34:45.492  2443  2443 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: QUALCOMM build                   : db3d445dbc, Ia06b22fa1a
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Build Date                       : 10/04/21
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Local Branch                     : 
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Remote Branch                    : 
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Remote Branch                    : 
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Reconstruct Branch               : 
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
08-21 23:34:45.502  2443  2475 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-21 23:34:45.505  2443  2475 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
08-21 23:34:45.513  2443  2475 W libc    : Access denied finding property "vendor.migl.d
```

**Comment by jing332** [comment]
下错包了吧？是带有arm64的apk名嘛？

**Comment by jing332** [comment]
找到原因了，安卓没把frp二进制执行文件移动到lib目录，我在开发环境没问题，发布版才有，奇了怪了。

**Comment by fcwys** [comment]
还是崩溃：
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Tombstone maker: 'xCrash 3.0.0'
Crash type: 'java'
Start time: '2023-08-22T09:04:44.811+0800'
Crash time: '2023-08-22T09:06:11.760+0800'
App ID: 'com.github.jing332.frpandroid'
App version: '1.23.082208 (24)'
Rooted: 'No'
API level: '33'
OS version: '13'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'Xiaomi'
Brand: 'Redmi'
Model: 'Redmi K40S'
Build fingerprint: 'Redmi/munch/munch:13/TKQ1.220807.001/V14.0.6.0.TLMCNXM:user/release-keys'
pid: 17416, tid: 17416, name: main  >>> com.github.jing332.frpandroid <<<

java stacktrace:
java.lang.RuntimeException: Unable to stop service com.github.jing332.frpandroid.service.FrpcService@c7d316d: java.lang.RuntimeException: WakeLock under-locked frp_android:FRPC
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4849)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.RuntimeException: WakeLock under-locked frp_android:FRPC
	at android.os.PowerManager$WakeLock.release(PowerManager.java:3018)
	at android.os.PowerManager$WakeLock.release(PowerManager.java:2980)
	at w4.b.onDestroy(FrpService.kt:12)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4829)
	... 9 more

logcat:
--------- tail end of log main (/system/bin/logcat -b main -d -v threadtime -t 200 --pid 17416 *:D)
--------- beginning of main
08-22 09:05:08.651 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:08.758 17416 17444 W Parcel  : Expecting binder but got null!
08-22 09:05:08.954 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.163 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.163 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.163 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.164 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.165 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.198 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.504 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.776 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.776 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.776 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.777 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:09.779 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.000 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.001 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.002 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.002 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.012 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.317 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.571 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.571 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.571 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.572 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.574 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.879 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.990 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.990 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.990 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:10.991 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.019 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.304 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.304 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.304 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.305 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.326 17416 17416 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-22 09:05:11.631 17416 17416 I HandWriti
```

**Comment by jing332** [comment]
OK,  是唤醒锁问题
